import React from 'react'
import './styles.css';

const Gist = (props) => {
const gist = props.gistData
let fname = Object.keys(gist.files)+"";  
  
   return (
   <>
    <li className = "card-list">
       
          <div className="card">
                    <div className="card-header">
                        <div className = "row">
                            <div className = "col-md-1 display">
                                <div className = "col-md-6">
                                <img className = "user-img" src={gist.owner.avatar_url}  />
                                </div> 
                                <div className = "col-md-6">
                                <b>{gist.owner.login}</b>
                                </div>   

                           
                            </div>
                            <div className = "col-md-5">
                           
                            </div>
                            <div className = "col-md-1">
                                <b>{Object.keys(gist.files).length} Files</b>
                            </div>
                            <div className = "col-md-1">
                                <a className = "card-a" href = {gist.forks_url} target = "_blank" title = {gist.forks_url}><b>Forks</b></a>
                            </div>
                            <div className = "col-md-1">
                                 <a className = "card-a" href = {gist.comments_url} target = "_blank" title = {gist.comments_url    }><b>Comments</b></a> 
                            </div>
                            <div className = "col-md-1">
                            <a className = "card-a" title = "Stars"><b>Stars</b></a> 
                            </div>

                        </div>
                    
                    </div>
                    <div className="card-body">
                       
                        <div className = "row">
                            <div className = "col-md-3">
                            <p className = "card-font">Created at: {gist.created_at}</p>
                            </div>
                            <div className = "col-md-3">
                            <p className = "card-font">Updated at at: {gist.updated_at}</p>
                            </div>
                        </div>
                        
                        <p className="card-text">Generated by <a className = "card-a" href = {gist.url} target = "_blank" title = {gist.url}><b>{gist.url}</b></a></p>

                        <p className = "card-text"><a className = "card-a"  >{fname}</a></p>
                      

                       
                                           
                        
                    </div>
            </div>

    </li>
    </> 
    
       
   
   );
}

export default Gist